version: '3.8'

services:
  wabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wabot
    volumes:
      - ./tokens:/app/tokens
      - ./media:/app/media
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: npm start

networks:
  default:
    driver: bridge
